import { MenuItem, CustomizationOption } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'smash-double',
    name: 'Double Redline Smash',
    description: 'Two smashed aged beef patties, double melted cheddar, secret redline burger sauce, butter-toasted brioche, crisp pickles.',
    price: 12.99,
    calories: 850,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    category: 'burgers',
    tags: ['SIGNATURE', 'CHEESY'],
    customizable: true,
  },
  {
    id: 'burger-inferno',
    name: 'Inferno BBQ Heat',
    description: 'Two spiced smash patties, melted pepper jack, sizzling applewood bacon, pickled jalapeños, and our signature fiery bourbon-BBQ glaze.',
    price: 14.50,
    calories: 980,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    category: 'burgers',
    tags: ['SPICY', 'MEAT-LOVER'],
    heatLevel: 'SPICY',
    customizable: true,
  },
  {
    id: 'burger-truffle',
    name: 'Street Truffle Grill',
    description: 'Smashed prime beef patty, melted Swiss cheese, flame-grilled wild mushrooms, caramelized onions, and premium black truffle aioli.',
    price: 15.00,
    calories: 780,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    category: 'burgers',
    tags: ['GOURMET', 'CHEESY'],
    customizable: true,
  },
  {
    id: 'wings-buffalo',
    name: 'Signature Hot-Rod Wings',
    description: 'Crispy bone-in jumbo wings tossed in our legendary house-fermented cayenne & garlic buffalo sauce, served with blue cheese dip.',
    price: 10.99,
    calories: 640,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
    category: 'wings',
    tags: ['SIGNATURE', 'SPICY'],
    heatLevel: 'SPICY',
    customizable: true,
  },
  {
    id: 'wings-bourbon',
    name: 'Smoky Bourbon Maple Wings',
    description: 'Slow-smoked hickory wings glazed in a rich Kentucky bourbon and pure Vermont maple reduction, topped with toasted sesame.',
    price: 11.50,
    calories: 710,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80',
    category: 'wings',
    tags: ['SMOKY', 'SWEET'],
    customizable: true,
  },
  {
    id: 'wings-ghost',
    name: 'Ghost Pepper Fire-Starter',
    description: 'Jumbo wings coated in our lethal ghost-pepper and habanero honey glaze. Served with a cool buttermilk ranch. We dare you.',
    price: 12.00,
    calories: 620,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80',
    category: 'wings',
    tags: ['SPICY', 'EXTREME-HEAT'],
    heatLevel: 'GHOST',
    customizable: true,
  },
  {
    id: 'fries-loaded',
    name: 'Redline Loaded Fries',
    description: 'Crispy skin-on sea salt fries, smothered in liquid craft beer cheese, chopped smoked bacon, dynamic jalapeño wheels, and green onions.',
    price: 7.99,
    calories: 590,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    category: 'sides',
    tags: ['CHEESY', 'SHARABLE'],
    customizable: true,
  },
  {
    id: 'sides-rings',
    name: 'Crusty Onion Rings',
    description: 'Thick-cut sweet yellow onions, hand-dipped in craft IPA beer batter and flash-fried until shatteringly crispy. Chipotle dip.',
    price: 5.50,
    calories: 450,
    image: 'https://images.unsplash.com/photo-1639024471283-2bc7b3c6a267?w=600&auto=format&fit=crop&q=80',
    category: 'sides',
    tags: ['CRISPY', 'VEGETARIAN'],
    customizable: false,
  },
  {
    id: 'drink-soda',
    name: 'Redline Craft Cane Soda',
    description: 'House-brewed premium cane sugar soda. Choose from Cherry Spark, Smoked Vanilla Cola, or Ginger Fire.',
    price: 3.50,
    calories: 140,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    category: 'drinks',
    tags: ['REFRESHING'],
    customizable: true,
  }
];

export const CUSTOMIZATION_OPTIONS: CustomizationOption[] = [
  { id: 'opt-extra-patty', name: 'Extra Smash Patty', price: 3.00, calories: 250, category: 'patty' },
  { id: 'opt-cheddar', name: 'Aged Cheddar Slice', price: 1.00, calories: 110, category: 'cheese' },
  { id: 'opt-bacon', name: 'Crispy Smoked Bacon', price: 1.75, calories: 90, category: 'toppings' },
  { id: 'opt-jalapeno', name: 'Pickled Jalapeños', price: 0.50, calories: 15, category: 'toppings' },
  { id: 'opt-grilled-mushrooms', name: 'Flame-Grilled Mushrooms', price: 1.25, calories: 40, category: 'toppings' },
  { id: 'opt-fried-egg', name: 'Sunny Side Up Egg', price: 1.50, calories: 90, category: 'toppings' },
  { id: 'opt-truffle-sauce', name: 'Extra Truffle Aioli', price: 0.75, calories: 120, category: 'sauce' },
  { id: 'opt-ghost-sauce', name: 'Drizzle Ghost-Pepper Fire', price: 0.75, calories: 45, category: 'sauce' },
];
